version: '3'

services: 
    frontend:
        image: local/frontend:latest
        build: 
            context: ./frontend
        ports: 
            - 3000:5000
        networks:
            interna:
              ipv4_address: 10.0.1.3
        
    apiserver:
        image: local/apiserver:latest
        build: 
            context: ./apiserver
        ports: 
            - 5000:5000
        networks:
            interna:
              ipv4_address: 10.0.1.4
    proxy:
        image: local/proxy:latest
        build: 
            context: ./proxy
        ports: 
            - 443:443
            - 80:80
        expose:
            - 443
            - 80
        volumes: 
            - type: bin
              source: /etc/letsencrypt
              target: /etc/letsencrypt
        networks:
          interna:
            ipv4_address: 10.0.1.2

networks:
  interna:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
